const KEY='lmcDados';
const state=JSON.parse(localStorage.getItem(KEY)||'{"posto":{},"produtos":[],"tanques":[],"bombas":[],"bicos":[],"entradas":[]}');
state.produtos=state.produtos||[];state.tanques=state.tanques||[];state.bombas=state.bombas||[];state.bicos=state.bicos||[];state.entradas=state.entradas||[];
state.tanques.forEach((t,i)=>{if(t.estoqueAtual===undefined)t.estoqueAtual=0;if(!t.id)t.id=Date.now()+i});
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateStatus()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function litros(v){return Number.parseFloat(String(v).replace(',','.'))||0}
function fmt(v){return litros(v).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function dataHoje(){return new Date().toISOString().slice(0,10)}
function dataBR(v){const p=String(v||'').split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:'—'}
function updateStatus(){const el=document.getElementById('systemStatus');if(el)el.textContent=state.posto.nome?`Posto: ${state.posto.nome}`:'Sistema inicial'}
function openModule(name){cards.classList.add('hidden');welcome.classList.add('hidden');module.classList.remove('hidden');if(name==='Configurações')renderPosto();else if(name==='Produtos')renderProdutos();else if(name==='Tanques')renderTanques();else if(name==='Bombas e Bicos')renderBombas();else if(name==='Entradas')renderEntradas();else renderPlaceholder(name)}
function back(){module.classList.add('hidden');cards.classList.remove('hidden');welcome.classList.remove('hidden')}
function renderPosto(){const p=state.posto;m('Configurações',`<h2>🏢 Cadastro do Posto</h2><p class="muted">Informe os dados básicos do estabelecimento.</p><form onsubmit="savePosto(event)"><div class="formgrid"><label>Nome / Razão Social<input id="postoNome" required value="${esc(p.nome)}"></label><label>CNPJ<input id="postoCnpj" value="${esc(p.cnpj)}"></label><label>Nome Fantasia<input id="postoFantasia" value="${esc(p.fantasia)}"></label><label>Endereço<input id="postoEndereco" value="${esc(p.endereco)}"></label><label>Cidade<input id="postoCidade" value="${esc(p.cidade)}"></label><label>UF<input id="postoUf" maxlength="2" value="${esc(p.uf)}"></label></div><div class="actions"><button class="primary">Salvar cadastro</button><button type="button" onclick="back()">Voltar</button></div></form>`)}
function savePosto(e){e.preventDefault();state.posto={nome:postoNome.value.trim(),cnpj:postoCnpj.value.trim(),fantasia:postoFantasia.value.trim(),endereco:postoEndereco.value.trim(),cidade:postoCidade.value.trim(),uf:postoUf.value.trim().toUpperCase()};save();alert('Cadastro do posto salvo.')}
function renderProdutos(){m('Produtos',`<h2>⛽ Produtos</h2><p class="muted">Cadastre os combustíveis utilizados nos tanques e movimentações.</p><form onsubmit="addProduto(event)"><div class="formgrid"><label>Nome do produto<input id="prodNome" required></label><label>Tipo<select id="prodTipo"><option>Gasolina</option><option>Etanol</option><option>Diesel</option><option>Outro</option></select></label></div><div class="actions"><button class="primary">Adicionar produto</button></div></form><div class="tablewrap"><table><thead><tr><th>Produto</th><th>Tipo</th><th>Ação</th></tr></thead><tbody>${state.produtos.length?state.produtos.map((p,i)=>`<tr><td>${esc(p.nome)}</td><td>${esc(p.tipo)}</td><td><button class="danger" onclick="removeProduto(${i})">Excluir</button></td></tr>`).join(''):'<tr><td colspan="3" class="empty">Nenhum produto cadastrado.</td></tr>'}</tbody></table></div><button onclick="back()">Voltar</button>`)}
function addProduto(e){e.preventDefault();const nome=prodNome.value.trim();if(!nome)return;if(state.produtos.some(p=>p.nome.toLowerCase()===nome.toLowerCase()))return alert('Produto já cadastrado.');state.produtos.push({nome,tipo:prodTipo.value});save();renderProdutos()}
function removeProduto(i){if(state.tanques.some(t=>t.produto===state.produtos[i].nome)||state.entradas.some(e=>e.produto===state.produtos[i].nome))return alert('Não é possível excluir um produto que já está vinculado a tanques ou entradas.');if(confirm('Excluir este produto?')){state.produtos.splice(i,1);save();renderProdutos()}}
function renderTanques(){m('Tanques',`<h2>🛢️ Tanques</h2><p class="muted">O estoque atual será atualizado pelas entradas e, na próxima etapa, pela movimentação diária.</p><form onsubmit="addTanque(event)"><div class="formgrid"><label>Número<input id="tanqueNumero" required type="number" min="1"></label><label>Produto<select id="tanqueProduto" required>${state.produtos.length?state.produtos.map(p=>`<option value="${esc(p.nome)}">${esc(p.nome)}</option>`).join(''):'<option value="">Cadastre produto primeiro</option>'}</select></label><label>Capacidade (L)<input id="tanqueCap" required type="number" min="0" step="0.01"></label></div><div class="actions"><button class="primary" ${state.produtos.length?'':'disabled'}>Adicionar tanque</button></div></form><div class="tablewrap"><table><thead><tr><th>Tanque</th><th>Produto</th><th>Capacidade</th><th>Estoque atual</th><th>Ação</th></tr></thead><tbody>${state.tanques.length?state.tanques.map((t,i)=>`<tr><td>${esc(t.numero)}</td><td>${esc(t.produto)}</td><td>${fmt(t.capacidade)} L</td><td><strong>${fmt(t.estoqueAtual)} L</strong></td><td><button class="danger" onclick="removeTanque(${i})">Excluir</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum tanque cadastrado.</td></tr>'}</tbody></table></div><button onclick="back()">Voltar</button>`)}
function addTanque(e){e.preventDefault();if(state.tanques.some(t=>String(t.numero)===String(tanqueNumero.value)))return alert('Número de tanque já cadastrado.');state.tanques.push({id:Date.now(),numero:tanqueNumero.value,produto:tanqueProduto.value,capacidade:litros(tanqueCap.value),estoqueAtual:0});save();renderTanques()}
function removeTanque(i){const t=state.tanques[i];if(state.entradas.some(e=>String(e.tanqueId)===String(t.id))||state.bicos.some(b=>String(b.tanqueId)===String(t.id)))return alert('Não é possível excluir um tanque que possui vínculos ou entradas registradas.');if(confirm('Excluir este tanque?')){state.tanques.splice(i,1);save();renderTanques()}}
function renderBombas(){m('Bombas e Bicos',`<h2>🔢 Bombas e Bicos</h2><p class="muted">Cadastre as bombas e os bicos e vincule cada bico ao produto e ao tanque.</p><div class="subsection"><h3>➕ Cadastrar bomba</h3><form onsubmit="addBomba(event)"><div class="formgrid"><label>Número da bomba<input id="bombaNumero" required type="number" min="1"></label><label>Identificação<input id="bombaNome" placeholder="Ex.: Bomba 01"></label></div><div class="actions"><button class="primary">Adicionar bomba</button></div></form></div><div class="subsection"><h3>⛽ Cadastrar bico</h3><form onsubmit="addBico(event)"><div class="formgrid"><label>Bomba<select id="bicoBomba" required>${state.bombas.length?state.bombas.map(b=>`<option value="${b.id}">${esc(b.nome)}</option>`).join(''):'<option value="">Cadastre uma bomba primeiro</option>'}</select></label><label>Número do bico<input id="bicoNumero" required type="number" min="1"></label><label>Produto<select id="bicoProduto" required>${state.produtos.length?state.produtos.map(p=>`<option value="${esc(p.nome)}">${esc(p.nome)}</option>`).join(''):'<option value="">Cadastre um produto primeiro</option>'}</select></label><label>Tanque<select id="bicoTanque" required>${state.tanques.length?state.tanques.map(t=>`<option value="${t.id}">Tanque ${esc(t.numero)} — ${esc(t.produto)}</option>`).join(''):'<option value="">Cadastre um tanque primeiro</option>'}</select></label></div><div class="actions"><button class="primary" ${state.bombas.length&&state.produtos.length&&state.tanques.length?'':'disabled'}>Adicionar bico</button></div></form></div><div class="tablewrap"><table><thead><tr><th>Bomba</th><th>Bico</th><th>Produto</th><th>Tanque</th><th>Ação</th></tr></thead><tbody>${state.bicos.length?state.bicos.map((b,i)=>`<tr><td>${esc(b.bombaNome)}</td><td>${esc(b.numero)}</td><td>${esc(b.produto)}</td><td>${esc(b.tanqueNome)}</td><td><button class="danger" onclick="removeBico(${i})">Excluir</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum bico cadastrado.</td></tr>'}</tbody></table></div><div class="subsection"><h3>Bombas cadastradas</h3><div class="tablewrap"><table><thead><tr><th>Número</th><th>Identificação</th><th>Ação</th></tr></thead><tbody>${state.bombas.length?state.bombas.map((b,i)=>`<tr><td>${esc(b.numero)}</td><td>${esc(b.nome)}</td><td><button class="danger" onclick="removeBomba(${i})">Excluir</button></td></tr>`).join(''):'<tr><td colspan="3" class="empty">Nenhuma bomba cadastrada.</td></tr>'}</tbody></table></div></div><button onclick="back()">Voltar</button>`)}
function addBomba(e){e.preventDefault();if(state.bombas.some(b=>String(b.numero)===String(bombaNumero.value)))return alert('Número de bomba já cadastrado.');state.bombas.push({id:Date.now(),numero:bombaNumero.value,nome:bombaNome.value.trim()||`Bomba ${bombaNumero.value}`});save();renderBombas()}
function addBico(e){e.preventDefault();const bomba=state.bombas.find(b=>String(b.id)===String(bicoBomba.value));const tanque=state.tanques.find(t=>String(t.id)===String(bicoTanque.value));if(!bomba||!tanque)return alert('Selecione bomba e tanque.');if(tanque.produto!==bicoProduto.value)return alert('O produto do bico deve ser o mesmo do tanque.');state.bicos.push({id:Date.now(),bombaId:bomba.id,bombaNome:bomba.nome,numero:bicoNumero.value,produto:bicoProduto.value,tanqueId:tanque.id,tanqueNome:`Tanque ${tanque.numero}`});save();renderBombas()}
function removeBomba(i){const id=state.bombas[i].id;if(state.bicos.some(b=>b.bombaId===id))return alert('Exclua primeiro os bicos vinculados a esta bomba.');if(confirm('Excluir esta bomba?')){state.bombas.splice(i,1);save();renderBombas()}}
function removeBico(i){if(confirm('Excluir este bico?')){state.bicos.splice(i,1);save();renderBombas()}}
function renderEntradas(){const produtos=state.produtos.map(p=>`<option value="${esc(p.nome)}">${esc(p.nome)}</option>`).join('');m('Entradas',`<h2>📥 Entrada de Combustível</h2><p class="muted">Registre cada recebimento. A quantidade será somada automaticamente ao estoque do tanque.</p><form onsubmit="addEntrada(event)"><div class="formgrid"><label>Data da entrada<input id="entradaData" required type="date" value="${dataHoje()}"></label><label>Nota fiscal<input id="entradaNota" required placeholder="Ex.: NF 123456"></label><label>Distribuidora<input id="entradaDistribuidora" required placeholder="Nome da distribuidora"></label><label>Produto<select id="entradaProduto" required onchange="syncEntradaTanque()">${produtos||'<option value="">Cadastre um produto primeiro</option>'}</select></label><label>Tanque<select id="entradaTanque" required></select></label><label>Quantidade recebida (L)<input id="entradaQuantidade" required type="number" min="0.01" step="0.01" placeholder="0,00"></label><label>Número do documento<input id="entradaDocumento" placeholder="Ex.: DANFE / CTRC / transporte"></label><label class="full">Observações<textarea id="entradaObservacoes" rows="3" placeholder="Informações adicionais sobre a entrega"></textarea></label></div><div id="entradaAviso" class="formnotice"></div><div class="actions"><button class="primary" ${state.produtos.length&&state.tanques.length?'':'disabled'}>💾 Registrar entrada</button><button type="button" onclick="back()">Voltar</button></div></form><div class="summary"><div><span>Entradas registradas</span><strong>${state.entradas.length}</strong></div><div><span>Total recebido</span><strong>${fmt(state.entradas.reduce((s,e)=>s+litros(e.quantidade),0))} L</strong></div></div><h3>Histórico de entradas</h3><div class="tablewrap"><table><thead><tr><th>Data</th><th>NF</th><th>Distribuidora</th><th>Produto</th><th>Tanque</th><th>Quantidade</th><th>Documento</th><th>Ação</th></tr></thead><tbody>${state.entradas.length?state.entradas.slice().sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(e=>`<tr><td>${dataBR(e.data)}</td><td>${esc(e.notaFiscal)}</td><td>${esc(e.distribuidora)}</td><td>${esc(e.produto)}</td><td>${esc(e.tanqueNome)}</td><td><strong>${fmt(e.quantidade)} L</strong></td><td>${esc(e.documento)||'—'}</td><td><button class="danger" onclick="removeEntrada(${state.entradas.indexOf(e)})">Excluir</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nenhuma entrada registrada.</td></tr>'}</tbody></table></div>`);syncEntradaTanque()}
function syncEntradaTanque(){const p=document.getElementById('entradaProduto'),t=document.getElementById('entradaTanque'),a=document.getElementById('entradaAviso');if(!p||!t)return;const atual=t.value;const opts=state.tanques.filter(x=>x.produto===p.value);t.innerHTML=opts.length?opts.map(x=>`<option value="${x.id}">Tanque ${esc(x.numero)} — ${esc(x.produto)} (${fmt(x.estoqueAtual)} L)</option>`).join(''):'<option value="">Nenhum tanque deste produto</option>';if(opts.some(x=>String(x.id)===String(atual)))t.value=atual;updateEntradaAviso()}
function updateEntradaAviso(){const t=document.getElementById('entradaTanque'),q=document.getElementById('entradaQuantidade'),a=document.getElementById('entradaAviso');if(!t||!q||!a)return;const tanque=state.tanques.find(x=>String(x.id)===String(t.value));if(!tanque){a.textContent='Nenhum tanque compatível com o produto selecionado.';return}const novo=tanque.estoqueAtual+litros(q.value);a.textContent=novo>litros(tanque.capacidade)?`⚠️ Atenção: estoque após entrada ${fmt(novo)} L, acima da capacidade de ${fmt(tanque.capacidade)} L.`:`Estoque após a entrada: ${fmt(novo)} L de ${fmt(tanque.capacidade)} L.`}
function addEntrada(e){e.preventDefault();const produto=entradaProduto.value,tanque=state.tanques.find(t=>String(t.id)===String(entradaTanque.value)),quantidade=litros(entradaQuantidade.value);if(!produto||!tanque)return alert('Selecione produto e tanque.');if(tanque.produto!==produto)return alert('O produto da entrada deve ser o mesmo do tanque.');if(quantidade<=0)return alert('Informe uma quantidade válida.');const novo=tanque.estoqueAtual+quantidade;if(novo>litros(tanque.capacidade)&&!confirm(`A entrada deixará o tanque com ${fmt(novo)} L, acima da capacidade de ${fmt(tanque.capacidade)} L. Deseja registrar mesmo assim?`))return;state.entradas.push({id:Date.now(),data:entradaData.value,notaFiscal:entradaNota.value.trim(),distribuidora:entradaDistribuidora.value.trim(),produto,tanqueId:tanque.id,tanqueNome:`Tanque ${tanque.numero}`,quantidade,documento:entradaDocumento.value.trim(),observacoes:entradaObservacoes.value.trim()});tanque.estoqueAtual=novo;save();alert(`Entrada registrada com sucesso.\n${fmt(quantidade)} L adicionados ao Tanque ${tanque.numero}.\nEstoque atual: ${fmt(novo)} L.`);renderEntradas()}
function removeEntrada(i){const e=state.entradas[i],q=litros(e.quantidade),tanque=state.tanques.find(t=>String(t.id)===String(e.tanqueId));if(tanque&&tanque.estoqueAtual<q)return alert('Não é possível estornar: o estoque atual do tanque é menor que esta entrada.');if(!confirm(`Excluir a entrada da NF ${e.notaFiscal||'sem número'} e estornar ${fmt(q)} L?`))return;if(tanque)tanque.estoqueAtual-=q;state.entradas.splice(i,1);save();renderEntradas()}
function renderPlaceholder(name){m(name,`<h2>${esc(name)}</h2><p class="muted">Este módulo será desenvolvido nas próximas etapas.</p><button onclick="back()">Voltar ao painel</button>`)}
function m(title,html){document.getElementById('module').innerHTML=html}
document.addEventListener('input',e=>{if(e.target&&e.target.id==='entradaQuantidade')updateEntradaAviso()});
save();updateStatus();
