const USUARIOS_KEY='lmcUsuarios';
const SESSION_USER_KEY='lmcUsuarioAtual';
const DEFAULT_USERS=[{id:'admin',nome:'Administrador',usuario:'admin',senha:'lmc2026',perfil:'Administrador'}];
function getUsuarios(){try{const u=JSON.parse(localStorage.getItem(USUARIOS_KEY)||'null');if(Array.isArray(u)&&u.length)return u}catch(e){}localStorage.setItem(USUARIOS_KEY,JSON.stringify(DEFAULT_USERS));return [...DEFAULT_USERS]}
function saveUsuarios(u){localStorage.setItem(USUARIOS_KEY,JSON.stringify(u))}
function usuarioAtual(){try{return JSON.parse(sessionStorage.getItem(SESSION_USER_KEY)||'null')}catch(e){return null}}
function perfilAtual(){return usuarioAtual()?.perfil||'Administrador'}
function pode(acao){const p=perfilAtual();if(p==='Administrador')return true;if(p==='Operador')return ['registrar','consultar','relatorios'].includes(acao);return ['consultar','relatorios'].includes(acao)}
function loginUsuario(usuario,senha){const u=getUsuarios().find(x=>x.usuario===usuario&&x.senha===senha);if(!u)return false;sessionStorage.setItem(SESSION_USER_KEY,JSON.stringify({id:u.id,nome:u.nome,usuario:u.usuario,perfil:u.perfil}));sessionStorage.setItem('lmcAuth','1');return true}
function logoutUsuario(){sessionStorage.removeItem(SESSION_USER_KEY);sessionStorage.removeItem('lmcAuth');location.reload()}
function renderUsuarios(){if(perfilAtual()!=='Administrador'){m('Usuários','<h2>👥 Usuários</h2><p class="formnotice">Somente o Administrador pode gerenciar usuários.</p><div class="actions"><button onclick="back()">Voltar</button></div>');return}const us=getUsuarios();m('Usuários',`<h2>👥 Usuários e Permissões</h2><p class="muted">Cadastre quem poderá acessar o LMC e defina o nível de acesso.</p><div class="subsection"><form onsubmit="addUsuario(event)"><div class="formgrid"><label>Nome<input id="usrNome" required></label><label>Usuário<input id="usrLogin" required></label><label>Senha<input id="usrSenha" type="password" minlength="4" required></label><label>Perfil<select id="usrPerfil"><option>Administrador</option><option>Operador</option><option>Consulta</option></select></label></div><div class="actions"><button class="primary">Adicionar usuário</button></div></form></div><div class="tablewrap"><table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Ação</th></tr></thead><tbody>${us.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.usuario)}</td><td>${esc(u.perfil)}</td><td>${u.usuario==='admin'?'<span class="muted">Principal</span>':`<button class="danger" onclick="removerUsuario('${esc(u.id)}')">Excluir</button>`}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhum usuário.</td></tr>'}</tbody></table></div><div class="actions"><button onclick="back()">Voltar</button></div>`)}
function addUsuario(e){e.preventDefault();const us=getUsuarios();const usuario=usrLogin.value.trim();if(us.some(u=>u.usuario.toLowerCase()===usuario.toLowerCase()))return alert('Este usuário já existe.');us.push({id:'u_'+Date.now(),nome:usrNome.value.trim(),usuario,senha:usrSenha.value,perfil:usrPerfil.value});saveUsuarios(us);alert('Usuário cadastrado.');renderUsuarios()}
function removerUsuario(id){if(!confirm('Excluir este usuário?'))return;saveUsuarios(getUsuarios().filter(u=>u.id!==id));renderUsuarios()}
window.renderUsuarios=renderUsuarios;window.loginUsuario=loginUsuario;window.logoutUsuario=logoutUsuario;window.pode=pode;window.perfilAtual=perfilAtual;
